### ISSUE TITLE
Bytes are not characters

### ISSUE THREAD

**Issue by bbuck** [felixangell/vident#2]
In several places through the project your documentation references the word "character" yet your code used the type `byte`. It's important to understand that in Go a `byte` is not a character, a `rune` is a character. And a `rune` can be larger than a single byte, in fact a rune is an `int32` while a `byte` is a `uint8`. 

Take this simple example into consideration:

```go
package main

import (
	"fmt"
	"unicode/utf8"
)

func main() {
	str := "Hello, 世界"
	// By bytes
	fmt.Println("Processing by byte")
	for i := 0; i < len(str); i++ {
		fmt.Printf("%d => %c\n", i, str[i])
	}
	
	// using range, not the best approach for lexing
	fmt.Println("Processing via range, which is rune-aware")
	for i, c := range str {
		fmt.Printf("%d => %c\n", i, c)
	}
	
	// using utf8, to do it manually
	fmt.Println("Processing via utf8")
	for i := 0; i < len(str); {
		r, s := utf8.DecodeRuneInString(str[i:])
		fmt.Printf("%d => %c\n", i, r)
		i += s
	}
}
```

[Playground](https://play.golang.org/p/IWtoLlCJRI).

I recommend you adjust your software before writing your tutorial to properly take utf8 encoding into consideration so that your teaching the correct method when discussing "characters."

Also, if you're interested in learning about it [this is a great read](http://www.joelonsoftware.com/articles/Unicode.html) to get started off with encodings.

Good luck with this language and your tutorial series.

**Comment by felixangell** [comment]
I was considering supporting unicode because Go makes this a lot easier with the Rune support. So perhaps I'll write it up some point, cheers :+1:

**Comment by bbuck** [comment]
My concern wasn't so much as support for it, but the fact you're planning on teaching it. I'm totally fine with you handling this however you want to in regards to your own personal projects and dealing with those consequences but the fact that you're introducing people into this with this chosen language you should make sure to teach everyone the proper way to handle certain aspects, in this case, characters. Go supports UTF8 by default (using the language provided constructs) and you have to violate that default to just support something like standard ASCII encodings. A language like C on the other hand supports ASCII by default and thus it's fine to teach that way.

Just for the sake of everyone who will read your blogs in the future, please do it right when teaching!

**Comment by felixangell** [comment]
Sure thing eh, I suppose I didn't think about then when I thought about writing the series. I kinda just chose Go on a whim, so I'm still new to it myself (if you can't tell haha) :+1:

**Comment by bbuck** [comment]
:+1:

**Comment by felixangell** [comment]
Finally got round to working on this, sorry it took so long school work is consuming all my time :-1:

**Comment by bbuck** [comment]
It's all good, you got it done which is great! Just keep it up when you can!
